### ISSUE TITLE
Can't update -- local_vulnerable_files.xml: checksums do not match

### ISSUE THREAD

**Issue by natv** [wpscanteam/wpscan#977]
I'm on Kali2.  Been using wpscan for a long time but starting about a week ago it won't update.

Error is:

[i] Updating the Database ...

[!] local_vulnerable_files.xml: checksums do not match

I downloaded wpscan via git to test that way but it requires a newer version of ruby, and not sure if updating that would break Metasploit or something else so I haven't updated ruby.

Thanks

**Comment by MukeshSingh28** [comment]
Similar Issue following are the details
<img width="562" alt="screen shot 2016-08-12 at 12 27 37 pm" src="https://cloud.githubusercontent.com/assets/18393040/17611175/42b30660-6088-11e6-8c80-9c82274e5a0e.png">

**Comment by jbertman** [comment]
Same issue here - seems that the database checksum is corrupted somehow. Fresh Kali 2.0 install updated to latest through apt
Current version: 2.8
Last DB update: 2015-08-08

![image](https://cloud.githubusercontent.com/assets/4664954/17623159/a4ab7472-606c-11e6-8111-a7a8068621ff.png)

**Comment by FireFart** [comment]
@natv @jbertman @MukeshSingh28 any guys from you running the git master version? I just implemented some more detailed exception output when updating (https://github.com/wpscanteam/wpscan/commit/22d69a1bf99b86103f26f39b9c1ad7c64a51f074). If anyone of you is running the git version, it would be great if you can update to the latest version and paste the output (as text, not screenshot)

Thanks!

**Comment by jbertman** [comment]
Unfortunately I am not, Kali's repo version helps with the Ruby dep, I'd be happy to try to merge those additions and give it a shot, though.

**Comment by FireFart** [comment]
@jbertman you could apply the diff file (https://github.com/wpscanteam/wpscan/commit/22d69a1bf99b86103f26f39b9c1ad7c64a51f074.diff) to /usr/share/wpscan with `patch < diff_file`. You can undo the patch afterwards using `patch -R < diff_file`

**Comment by jbertman** [comment]
@FireFart The file seems to have changed, but otherwise same issue:

```
root@kali:~# wpscan --update -v
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Already Up-To-Date
[+] Checking local_vulnerable_files.xsd
  [i] Already Up-To-Date
[+] Checking plugins_full.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 284540fc139aaeafd4a8d9e18e554c0bc6bbbba6971674debc1e1552a25444f640e85021eb3ff1c6b5410fb16204295555b376cdcb515ce3aa895b966db692ce
B唃�/�����R�n��1�h�\�ܦ���Sf<��d��@?)��x͠��}�1'?I���&F�\{�5�~�u��"�}��
  [i] Restoring Backup due to error
  [i] Deleting Backup

[!] plugins_full.txt: checksums do not match
[!] Trace:
[!] /usr/share/wpscan/lib/common/db_updater.rb:111:in `block in update'
/usr/share/wpscan/lib/common/db_updater.rb:91:in `each'
/usr/share/wpscan/lib/common/db_updater.rb:91:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:454:in `<main>'
```

**Comment by FireFart** [comment]
@jbertman jeah patching failed so there is no output :/
To get git master working without messing up your kali installation you can use the RVM method. This puts all dependencies in a wpscan subfolder in your home directory so the system intallation is not touched.
You can find the instructions here:
https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended

**Comment by jbertman** [comment]
@FireFart I wanted to initially avoid using the RVM method so I could keep with the kali repo, but just using the method works fine for me. If there's a fix for the kali version, that's great. I'll use this in the meantime.

**Comment by FireFart** [comment]
@ethicalhack3r @jbertman @MukeshSingh28 @natv @Joshuahobby @eliddell1 @sonirico are you guys still having troubles updating? I implemented a "clear complete cache" once a day for now.

We are currently looking into switching our CDN so these might resolve your isseus too

**Comment by Joshuahobby** [comment]
Yes i still have a Trouble in updating it, you told me to use it on GitHub  but i didn't got how to do it, 
Please if it is possible may i get the Step by step of How i can update it,
NB: I am a beginner in GitHub

**Comment by FireFart** [comment]
@Joshuahobby we are currently switching CDN which hopefully resolves all issues

**Comment by Joshuahobby** [comment]
That means I can now update it how??

**Comment by FireFart** [comment]
`./wpscan --update` once we are finished

**Comment by Joshuahobby** [comment]
When are you gonna be done with it??

**Comment by FireFart** [comment]
The upgrade is now finished, all should be working without caching errors
